---
title: " Effort Estimation"
author: "Doug & Laurie"
date: "25/05/2015"
output: ioslides_presentation
---

# SHORT-TERM CONTRACT 
## A MODELING APPROACH TO ESTIMATE OVERALL ATLANTIC EFFORT BY TIME-AREA STRATA (EFFDIS)

# Objectives

Background: The International Commission for the Conservation of Atlantic Tunas (ICCAT) (www.iccat.int), an intergovernmental organization whose Secretariat headquarters is based in Madrid, Spain, is seeking to contract an expert to develop a modeling approach to estimate overall Atlantic long-line (LL), bait-boat (BB) and Purse Seine (PS) effort by time-area strata (EFFDIS). Based on the ICCAT fisheries data currently available at the Secretariat, the expert should implement this approach to generate a database of historic and current fishing effort distribution that meets the stated needs of the ICCAT Standing Committee on Research and Statistics (SCRS).  This update of the EFFDIS dataset is critical, especially with regard to by-catch evaluations.  

Proposal: The Contractor (Dr Doug Beare) proposes to develop a robust statistical modeling approach to estimate overall Atlantic fishing effort stratified by flag/fleet, gear, area (5ºx5º degree square grid), year and month (starting in 1950).  The Contractor will update the current EFFDIS estimations for longline (LL) gear (1950 to 2014) using the new modeling approach, and then develop EFFDIS  estimation procedures for baitboat (BB) and purse-seine (PS) gears with the appropriate units of effort.  The Contractor will work under the overall guidance of the ICCAT Executive Secretariat in collaboration with the Assistant Executive Secretary and the Research and Statistics Department.  Tangible deliverables will take the form of the outputs summarized below. The Contractor will complete the work within a period of six months and produce the final deliverables no less than one week before the 2015 Sub-Committee on Ecosystems meets.

Recommendations for improving EFFDIS estimation: The SGECO Working group recently made a series of recommendations for improving EFFDIS that will be taken into consideration by the Contractor at all stages.  Firstly the approach developed will examine seasonality in more detail. In particular data should be re-submitted by month and methods should acknowledge that dependence on seasonality interacts with the spatial and long-term variables, ie. seasonal patterns/shapes can be different each year and in different locations.  Spatial resolution is also an important consideration.   In theory the methods developed should begin at the finest level of spatial aggregation at which the data are available. This is also important for estimating variance and understanding the underlying sampling activities that actually generated the data.  In practice, however, this will all depend on the quality of the data available to the Contractor. At the moment data are available at a relatively course level (5ºx5º degree square grid) and any simulations undertaken to assess the impact of spatial (and temporal) aggregation on effort estimations will, perforce, use this as the starting point.  The Contractor will also use ICCAT networks to gain access to any relevant historical data and store them in the appropriate formats with metadata etc.  This extra information will be exploited in the methods developed to improve EFFDIS effort estimation. An important aspect of the current EFFDIS estimation relates to the assumptions concerning species composition of the catches.  These will be investigated by the Contractor and improvements made after seeking advice/feedback from the ICCAT Secretariat.  As part of the effort estimation procedure the Contractor will study the longline fleet operations, dynamics and behavior. Profiles summarizing how operations vary among long-line fleets will be used to inform, and improve EFFDIS estimations. Vessel Monitoring System (VMS) data will be used for the profiling, if available.  The assumptions relating to how the effort data are raised, eg. by using overall catch statistics are also crucial and these will be explored by the Contractor.   

Bait boat (BB) and purse-seine (PS) gears also take substantial quantities of tuna and tuna-like fish in the Atlantic and Mediterranean fisheries. Fishing strategies vary substantially between these fisheries and effort clearly cannot be quantified in the same way for each. Purse-seine fisheries, for example, are problematic since a large proportion of the time at sea is spent hunting for the fish and the actual catch can be taken in a very short period of time. The Contractor will, however, build effort estimates for these gears into EFFDIS.  Uncertainty around the effort estimates will be built into the estimation procedures. EFFDIS effort estimation will be dependent on a complex series of steps and assumptions. In this situation it is usually most sensible to estimate uncertainty/variance using non-parametric methods, e.g. bootstrapping, but the Contractor will explore parametric options too. The Contractor will also undertake to cross-validate the EFFDIS estimates using other relevant information where available, eg. VMS data.

Workplan: The Contractor will visit ICCAT in Madrid after the contract is signed. The purpose of the trip will be to obtain all the relevant data and review the methods for EFFDIS estimation and write documented R code to mimic the current procedure. The Contractor will then develop  ‘strawman’ methodologies for estimating fishing effort for one fleet/flag country, eg. Taiwan, and seek feedback from experts involved in WGSAM (Stock Assessment Methods Working Group), The Sharks Species Working Group, and the 2015 Sub-Committee on Ecosystems.  Once a method is approved for one fleet the Contractor will then adapt it to the other fleets to produce global estimates.  When the ICCAT Secretariat is fully satisfied the Methods/User Guides/Databases and Documentation for the updated EFFDIS, the Contractor will present the work at the 2015 Sub-Committee meeting on Ecosystems.

The Contractor will develop the estimation procedure using a bona-fide online SQL relational database allowing remote uploading and filtering/checking of new data.  Since the EFFDIS data are spatially-resolved a relational database which can handle common forms of spatial data (e.g. shapefiles and rasters)  and deal with spatial explicit queries will be used by the Contractor, e.g http://boundlessgeo.com/solutions/solutions-software/postgis/.  SQL, however, is not really an appropriate tool for statistical modeling for which programs like R are much better suited. There are R packages available (http://www.omegahat.org/RSPostgres/RPostgres.pdf) for PostGreSQL, however, that allow R-scripts to be triggered as part of SQL queries/scripts which the Contractor proposes as a potential option.  This, however, is completely flexible and the final choice of software (and hardware) will be guided by the ICCAT Secretariat.

# Time line
## Time line
